site_name: "LeRobot"
nav:
  - index.md
  - script_sequences.md
  - hardware_interfaces.md
  - policy_interfaces.md
plugins:
  - search
  - with-pdf:
      output_path: lerobot_documentation.pdf
  - mkdocstrings:
      handlers:
        python:
          load_external_modules: true
          options:
            members_order: source
            show_source: false
  - kroki:
      FencePrefix: ""
      FileTypeOverrides:
        mermaid: png

theme: readthedocs

docs_dir: "src_docs/src"
site_dir: "src_docs/site"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@11.12.0/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@11.12.0/dist/mermaid.min.js
