site_name: "LeRobot"
<<<<<<< HEAD
=======
nav:
  - index.md
  - hardware.md
  - policies.md
>>>>>>> 5a5ab0b (add: settings of mkdocs)

plugins:
  - search
  - with-pdf:
      output_path: lerobot_documentation.pdf
  - mkdocstrings:
      handlers:
        python:
          load_external_modules: true
          options:
            members_order: source
            show_source: false

theme: readthedocs

docs_dir: "src_docs/src"
site_dir: "src_docs/site"
